### ISSUE TITLE
DefaultCPUAllocator

### ISSUE THREAD

**Issue by rvssridatta** [MaximeVandegar/Papers-in-100-Lines-of-Code#10]
Hi Maxime

I tried to run the repo as it is. But I am getting the below error. Is there any resolution to resolve this issue. I am using my CPU instead of my GPU is that the cause for this issue.

![image](https://github.com/MaximeVandegar/Papers-in-100-Lines-of-Code/assets/65171912/20c905b2-4434-4d74-8ab9-561896fbe4a7)

" RuntimeError: [enforce fail at C:\b\abs_bao0hdcrdh\croot\pytorch_1675190257512\work\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 1981808640 bytes."

The error is while running the test function(below 2 lines of the code).

**Comment by IamShubhamGupto** [comment]
A similar issue - https://github.com/CompVis/stable-diffusion/issues/329
