### ISSUE TITLE
100-lines K-planes is NOT equals to official K-planes?

### ISSUE THREAD

**Issue by yuedajiong** [MaximeVandegar/Papers-in-100-Lines-of-Code#12]
e.g.
1) with 'Varying Appearance'
2) with 'Dynamic Volums'

this 100-lines version just implemented: Static-Volums?     3-planes + Hadamard-Product + 2 encoders (spatially-localized to  density and ...;  ... and direction to RGB)

**Comment by MaximeVandegar** [comment]
Hi, excuse me for the delayed answer. Yes, the implementation focused on 3D reconstruction (static scenes) and does not include appearance embedding
