### ISSUE TITLE
shoudl be if __name__ == '__main__':

### ISSUE THREAD

**Issue by x06lan** [MaximeVandegar/Papers-in-100-Lines-of-Code#13]
https://github.com/MaximeVandegar/Papers-in-100-Lines-of-Code/blob/d8747adf9cfa572f6543a6886d20c9988d6c511b/Neural_Radiance_Fields_Without_Known_Camera_Parameters/nerfmm.py#L180

**Comment by GSORF** [comment]
I can confirm this issue.

**Comment by MaximeVandegar** [comment]
Solved, thank you! :)
