### ISSUE TITLE
Question on Using Custom Datasets with FastNeRF 

### ISSUE THREAD

**Issue by KamranNiroomand** [MaximeVandegar/Papers-in-100-Lines-of-Code#19]
Hi,

I've been working with FastNeRF and I am interested in extending its functionality to work with custom datasets. I've noticed that the code currently works with specific pickle files, and I'm looking for guidance on how to adapt it for different data formats or sources.

Could you provide some insights or documentation on how to go about this? Are there specific requirements or constraints for the data that I should be aware of when trying to use my own datasets?

Any help or pointers you could provide would be greatly appreciated.

Thanks for your great work on this project!

Kamran

**Comment by MaximeVandegar** [comment]
Hi @KamranNiroomand, you might also be interested in this video https://youtu.be/ujkec9KBnI8.

Best,
Maxime
