### ISSUE TITLE
Scaling value

### ISSUE THREAD

**Issue by bondrewd** [MaximeVandegar/Papers-in-100-Lines-of-Code#20]
Hi! Thank you very much for sharing this repo! It is very helpful for understanding all the different models out there!

Now I'm trying to understand DDPMs and found that in the attention block, you set the score value of the NIN block to 0.0. Since this NIN block is applied to the last value of the attention block, I think it makes the whole computation equal to 0.0, making the whole attention block equivalent to the identity. Maybe a scaling factor different from zero should be used here? 

And why do you prefer applying the NIN block compared to 2D convolutions with kernel size (1,1), stride (1,1), and zero padding?

Thank you!

https://github.com/MaximeVandegar/Papers-in-100-Lines-of-Code/blob/2decf0d6e672f2167d56aeb6e6ba273cd7bb84a1/Denoising_Diffusion_Probabilistic_Models/unet.py#L125

**Comment by MaximeVandegar** [comment]
Hi @bondrewd.

Excuse me for the delayed answer. The choice of using the NIN block, and setting the scale to 0 comes from the official paper implementation. 

It is common in Diffusion U-Net and ResNets to initialise blocks to the identity function. This is discussed in the paper _Scalable Diffusion Models with Transformers_ if you are interested :)
