### ISSUE TITLE
How about trying this: https://github.com/google-research/nerf-from-image

### ISSUE THREAD

**Issue by 013292** [MaximeVandegar/Papers-in-100-Lines-of-Code#4]
Hey man,
Very nice work. 
Any interests to replicate [this work ](https://github.com/google-research/nerf-from-image)? I found it very large and difficult.
Never mind if not interested :-)

**Comment by MaximeVandegar** [comment]
Hi, thank you for pointing out this work to me.

I do not plan to implement it in the near future, but I will keep it in mind. Maybe I will add it at some point :)
